builds:
  - id: sigmac
    binary: sigmac
    main: ./sigmac
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64

archives:
  - replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
    format: zip

snapshot:
  name_template: "{{ .Tag }}-next"
